name: ARM

on:
  push:
    branches:
      - arm_wheel

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux-cross:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
        target: [aarch64, armv7, s390x, ppc64le]

    steps:
    - uses: actions/checkout@v3
    - name: Build Wheels
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ matrix.target }}
        manylinux: auto
        args: -i ${{ matrix.python }} --release --out dist

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist
            
