name: ARM

on:
  push:
    branches:
      - arm_wheel

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  arm64:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          install: |
            apt-get update
            apt-get install -y curl software-properties-common
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            
            add-apt-repository ppa:deadsnakes/ppa
            apt-get update
            apt-get install -y python3.9

          run: |
            uname -a
            source "$HOME/.cargo/env"
            rustup -V

            python -V
            python3.9 -V
            
