name: ARM

on:
  push:
    branches:
      - arm_wheel

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  arm64:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ["3.7", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu_latest
          run: |
            uname -a
